sudo: required
services:
        - docker
before_install:
        - docker build -t tonyhong568/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true tonyhong568/react-test npm test 
 
after_success:
        - docker build -t tonyhong568/multi-client ./client
        - docker build -t tonyhong568/multi-nginx ./nginx
        - docker build -t tonyhong568/multi-server ./server
        - docker build -t tonyhong568/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push tonyhong568/multi-client
        - docker push tonyhong568/multi-nginx
        - docker push tonyhong568/multi-server
        - docker push tonyhong568/multi-worker



